// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6MaviuOpEX2uly_UUehvIZBbJRrqmJm4',
    appId: '1:761752124176:web:a84c00dda886da8bb74395',
    messagingSenderId: '761752124176',
    projectId: 'zoomer-translato',
    authDomain: 'zoomer-translato.firebaseapp.com',
    storageBucket: 'zoomer-translato.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInXyJfWYU4k8qf18Lo8DgPhIGE1nEKOs',
    appId: '1:761752124176:android:86215c6c682d4a16b74395',
    messagingSenderId: '761752124176',
    projectId: 'zoomer-translato',
    storageBucket: 'zoomer-translato.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwEv6IH5B-GstUE3Mv5dgl5lurulo4qPI',
    appId: '1:761752124176:ios:41b668aea1669161b74395',
    messagingSenderId: '761752124176',
    projectId: 'zoomer-translato',
    storageBucket: 'zoomer-translato.firebasestorage.app',
    iosBundleId: 'zoomertranslator.app',
  );
}
